### ISSUE TITLE
Implementar "Reporte Estadisticas"

### ISSUE THREAD

**Issue by MatSebMan** [hanoii/tallerproyectos2#122]
Implementar una nueva vista de nombre "Reporte Estadisticas"

Criterios de aceptación:

El mismo luego de seleccionar un mes debe mostrar:
- [ ] Ventas del mes en curso y comparación con las ventas del mismo mes en el año anterior. La siguiente ilustracion muestra lo esperado:
![image](https://cloud.githubusercontent.com/assets/8824791/15398112/cb79594e-1db8-11e6-924b-fbe3af6e34f6.png)

- [ ] Top 10 de marcas mas vendidas sobre el mes seleccionado. El mismo debe mostrar los campos "Marca", "Cantidad vendida", "$ Total", "% Total"

- [ ] Top 10 vendedores. La siguiente ilustracion muestra lo esperado:
![image](https://cloud.githubusercontent.com/assets/8824791/15398400/dd6782e2-1db9-11e6-8043-9a315ce03dd2.png)

El reporte deberá contener los siguientes filtros:
- [ ] Vendedores. Del mismo se puede seleccionar un vendedor en particular, o todos.
- [ ] Mes
- [ ] Año

Otros:
- [ ] Los filtros aplican para todas las gráficas del mismo reporte
- [ ] Por defecto los filtros de año y mes mostrarán el período actual
- [ ] Por defecto el filtro de vendedores mostrará "todos"
- [ ] El reporte es visible solo para el perfil "administrador"
- [ ] El reporte se mostrará en su totalidad para los valores por defecto al ingresar a la vista. Luego podrá cambiarse por medio de un ajuste de filtros
- [ ] Cualquier cambio de filtros será reflejado en el reporte instantáneamente
- [ ] El reporte de vendedores deberá mostrar al seleccionar la porción del gráfico correspondiente a un vendedor determinado:
  - [ ] El nombre del vendedor
  - [ ] El valor en $ de la venta
- [ ] Cada gráfico mostrará un código de colores que permita diferenciar los valores incluidos
- [ ] Cada reporte mostrará sus resultados según el valor en $ de las ventas
- [ ] El filtro por vendedores deberá mostrarse como una lista tipo drop down con paginado
- [ ] El filtro por vendedores deberá incluir un campo de búsqueda
- [ ] El filtro por mes deberá mostrarse como una lista tipo drop down
- [ ] El filtro por año deberá mostrarse como una lista tipo drop down que incluya el año en curso y los ultimos 10 años
- [ ] Al seleccionarse un período que no contenga información, el sistema mostrara el mensaje informativo correspondiente
